# Generated by Django 4.1.2 on 2022-10-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='request',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='item',
            field=models.CharField(max_length=50),
        ),
    ]
