# Generated by Django 4.1.2 on 2022-10-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0003_rename_request_requisition_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='department',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
