# Generated by Django 4.1.2 on 2022-10-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0004_alter_requisition_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='item',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='seller_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='seller_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
