# Generated by Django 4.1.2 on 2022-10-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0006_alter_requisition_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
