# Generated by Django 4.1.2 on 2022-10-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0007_alter_requisition_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='department',
            field=models.CharField(default='department', max_length=50),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='item',
            field=models.CharField(default='item', max_length=50),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='price',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='seller_address',
            field=models.CharField(default='address', max_length=50),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='seller_name',
            field=models.CharField(default='name', max_length=50),
        ),
    ]
