# Generated by Django 4.1.2 on 2022-10-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0008_alter_requisition_department_alter_requisition_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='department',
            field=models.CharField(blank=True, default='department', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='item',
            field=models.CharField(blank=True, default='item', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='price',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='seller_address',
            field=models.CharField(blank=True, default='address', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='seller_name',
            field=models.CharField(blank=True, default='name', max_length=50, null=True),
        ),
    ]
