# Generated by Django 4.1.2 on 2022-10-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0010_alter_requisition_department_alter_requisition_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
