# Generated by Django 4.0.3 on 2022-11-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0012_requisition_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
